### ISSUE TITLE
CSV dataset cannot add a variable with "no MissingValue" error

### ISSUE THREAD

**Issue by vassilyl** [predictionmachines/SDSlite#38]
Repro:

```
#r "nuget:sdslite"

using Microsoft.Research.Science.Data;
using (var sdsout = DataSet.Open("out.csv", ResourceOpenMode.Create)){
    sdsout.AddVariable<double>("a","a");
}
```

Error message:

```
Error: System.Collections.Generic.KeyNotFoundException: The given key 'MissingValue' was not present in the dictionary.
at Microsoft.Research.Science.Data.MetadataDictionary.get_Item(String key, SchemaVersion version)
at Microsoft.Research.Science.Data.CSV.CsvDataSet.SaveMetadataForVariable(StreamWriter sw, Dictionary`2 idToColumn, Variable v)
at Microsoft.Research.Science.Data.CSV.CsvDataSet.SaveCsv(Stream outputStream, ICollection`1 variables)
at Microsoft.Research.Science.Data.CSV.CsvDataSet.SaveToFile(ICollection`1 vars, String fileName)
at Microsoft.Research.Science.Data.CSV.CsvDataSet.OnPrecommit(Changes changes)
at Microsoft.Research.Science.Data.DataSet.Precommit(Changes proposedChanges)
at Microsoft.Research.Science.Data.DataSet.ApplyChanges(Changes proposedChanges)
at Microsoft.Research.Science.Data.DataSet.Commit()
at Microsoft.Research.Science.Data.DataSet.TryCommit()
at Microsoft.Research.Science.Data.DataSet.OnDataSetChanged(DataSetChangeAction action, Changes changes, Object target)
at Microsoft.Research.Science.Data.DataSet.FireEventChanged(DataSetChangeAction action, Changes changes, Object target)
at Microsoft.Research.Science.Data.DataSet.AddVariableToCollection(Variable var)
at Microsoft.Research.Science.Data.DataSet.AddVariable[DataType](String varName, String[] dims)
```

This only happens when the attribute `appendMetadata` is `true` (default). Until this is fixed CSV files should be created without appending metadata, e.g. `DataSet.Open("out.csv?appendMetadata=false", ResourceOpenMode.Create)`

**Comment by vassilyl** [comment]
Another workaround is to disable auto-commit and explicitly set `MissingValue` for each new variable, e.g.

```C#
using (var sdsout = DataSet.Open("out.csv", ResourceOpenMode.Create)){
    sdsout.IsAutocommitEnabled = false;
    var v = sdsout.AddVariable<double>("a","a");
    v.MissingValue = double.NaN;
}
```
